### ISSUE TITLE
script looking for room instead of config nest-channel

### ISSUE THREAD

**Issue by nileplumb** [Ben-13/NestPoster#1]
usage: nestposter.py [-h] --db-name DB_NAME --db-user DB_USER --db-pass
                     DB_PASS [--db-host DB_HOST] [--db-port DB_PORT] --header
                     HEADER --footer FOOTER --token TOKEN --room ROOM
nestposter.py: error: the following arguments are required: --room

**Comment by hunch-13** [comment]
woops, was having an issue and while testing i missed this.  Fixed now (to use nest-channel)
