### ISSUE TITLE
Script hard coded to monman database, change to config database (and potentially pokedex database variable to config too)

### ISSUE THREAD

**Issue by nileplumb** [Ben-13/NestPoster#2]
c.execute("""SELECT p.name as "Park Name", d.pokemon, p.pokemon_count as "Total Seen", format(p.pokemon_avg,0) FROM monman.nests p LEFT JOIN pokedex.pokedex d ON p.pokemon_id = d.pokemon_id where p.pokemon_avg ORDER BY p.pokemon_count DESC;""")

**Comment by hunch-13** [comment]
fixed to use variables
